stages:
  - build
  - simplelexer
  - lexer
  - generatedlexer
  - descentparser
  - generatedparser
  - astparser
  - visitors
  - codegenerator

build_all:
  stage: build
  image: czen/ubuntu_xbuild
  script:
    - ./prebuild.sh
    - ./build.sh
  tags:
    - docker
  #artifacts:
  #  paths:
  #    - ./NunitReportParser/bin/Debug/NunitReportParser.exe
  #    - ./TestSimpleLexer/bin/Debug/TestSimpleLexer.dll
  #    - ./TestLexer/bin/Debug/TestLexer.dll
  #    - ./TestGeneratedLexer/bin/Debug/TestGeneratedLexer.dll
  #    - ./TestDescentParser/bin/Debug/TestDescentParser.dll
  #    - ./TestGeneratedParser/bin/Debug/TestGeneratedParser.dll
  #    - ./TestASTParser/bin/Debug/TestASTParser.dll
  #    - ./TestVisitors/bin/Debug/TestVisitors.dll
  #    - ./TestCodeGenerator/bin/Debug/TestCodeGenerator.dll
  #  expire_in: 1 week


testsimplelexer:
  stage: simplelexer
  image: czen/ubuntu_xbuild
  script:
    - ./prebuild.sh
    - ./build.sh
    - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --labels=ON TestSimpleLexer/bin/Debug/TestSimpleLexer.dll
    - mono NunitReportParser/bin/Debug/NunitReportParser.exe ${CI_PROJECT_DIR} ${GITLAB_USER_LOGIN}
  tags:
    - docker
  
testlexer:
  stage: lexer
  image: czen/ubuntu_xbuild
  script:
    - ./prebuild.sh
    - ./build.sh
    - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --labels=ON TestLexer/bin/Debug/TestLexer.dll
    - mono NunitReportParser/bin/Debug/NunitReportParser.exe ${CI_PROJECT_DIR} ${GITLAB_USER_LOGIN}
  tags:
    - docker

testgeneratedlexer:
  stage: generatedlexer
  image: czen/ubuntu_xbuild
  script:
    - ./prebuild.sh
    - ./build.sh
    - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --labels=ON TestGeneratedLexer/bin/Debug/TestGeneratedLexer.dll
    - mono NunitReportParser/bin/Debug/NunitReportParser.exe ${CI_PROJECT_DIR} ${GITLAB_USER_LOGIN}
  tags:
    - docker    

testdescentparser:
  stage: descentparser
  image: czen/ubuntu_xbuild
  script:
    - ./prebuild.sh
    - ./build.sh
    - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --labels=ON TestDescentParser/bin/Debug/TestDescentParser.dll
    - mono NunitReportParser/bin/Debug/NunitReportParser.exe ${CI_PROJECT_DIR} ${GITLAB_USER_LOGIN}
  tags:
    - docker        

testgeneratedparser:
  stage: generatedparser
  image: czen/ubuntu_xbuild
  script:
    - ./prebuild.sh
    - ./build.sh
    - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --labels=ON TestGeneratedParser/bin/Debug/TestGeneratedParser.dll
    - mono NunitReportParser/bin/Debug/NunitReportParser.exe ${CI_PROJECT_DIR} ${GITLAB_USER_LOGIN}
  tags:
    - docker            

testastparser:
  stage: astparser
  image: czen/ubuntu_xbuild
  script:
    - ./prebuild.sh
    - ./build.sh
    - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --labels=ON TestASTParser/bin/Debug/TestASTParser.dll
    - mono NunitReportParser/bin/Debug/NunitReportParser.exe ${CI_PROJECT_DIR} ${GITLAB_USER_LOGIN}
  tags:
    - docker                

testvisitors:
  stage: visitors
  image: czen/ubuntu_xbuild
  script:
    - ./prebuild.sh
    - ./build.sh
    - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --labels=ON TestVisitors/bin/Debug/TestVisitors.dll
    - mono NunitReportParser/bin/Debug/NunitReportParser.exe ${CI_PROJECT_DIR} ${GITLAB_USER_LOGIN}
  tags:
    - docker                

testcodegenerator:
  stage: codegenerator
  image: czen/ubuntu_xbuild
  script:
    - ./prebuild.sh
    - ./build.sh
    - mono packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --labels=ON TestCodeGenerator/bin/Debug/TestCodeGenerator.dll
    - mono NunitReportParser/bin/Debug/NunitReportParser.exe ${CI_PROJECT_DIR} ${GITLAB_USER_LOGIN}
  tags:
    - docker                    
  